### PR TITLE
Distributed training cleanup

### PR DESCRIPTION
**Pull request by chester-leung**
* Remove apify calls -- now all machines running on ACC must be on same subnet to communicate
* Add troubleshooting section to `get_started` documentation
* Clean up `distr-training.py` for cleaner output

### CODE REVIEW

**Review by podcastinator — COMMENTED** [review]
LGTM for the most part. The config file's cached version needs to be forcefully removed, however, over and above adding it to gitignore. However, I think it might be better to commit a version of hosts.config that simply has some commented lines with instructions on how/ what to add? 
E.g. 
\# Add the IP address with SSH port of each machine in the cluster, one machine per line. For example:
\# 127.0.0.1:22

What do you think?

**Comment by chester-leung** [comment]
There's not really a "comment" per se, as the tracker just reads in the config file line by line, expecting each line to be an IP and port. 

Maybe we can actually completely remove the hosts.config file from the codebase, then in the documentation make a bold note saying that users should add a config file with the IPs of nodes in the cluster, along with an example of the config file itself?

**Comment by podcastinator** [comment]
Ah I see. I'd rather keep some version of the file, instead of completely removing it. 
How about checking it in with "127.0.0.1:22"?

**Review by podcastinator — APPROVED** [review]
Thanks!

**Pull request merged**
