### PR TITLE
Add additional resources to readme

### PR DESCRIPTION
**Pull request by chester-leung**
Add links to CCS workshop paper, TDS blog post, RISE Camp Youtube Walkthrough, and Docker image to be used for local development

### CODE REVIEW

**Review by podcastinator — APPROVED** [review]
This is great, thanks!

**Review by podcastinator — COMMENTED** [review]
Should we add this to the docs as well?

**Comment by chester-leung** [comment]
There's a problem with documentation rendering - I'll push a fix in a bit

**Comment by chester-leung** [comment]
Fixed

**Pull request merged**
